apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    env: dev
  namespace: default
spec:
  selector:
    project: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort