apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: app1
  source:
    path: "HelmChart/"
    repoURL: "git@github.com:newmandnn/ArgoCD.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "container.image"
          value: 877879097973.dkr.ecr.eu-central-1.amazonaws.com/demo-app

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
