---
#----------------------------------------------------------------
# Highly Available mode with autoscaling require minimum 3 nodes!
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  config:
    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: 
          hs = {}
          hs.status = "Healthy"
          return hs

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
